services:
  pgsql:
    image: pgvector/pgvector:pg16
    container_name: pgsql
    environment:
      POSTGRES_USER: zhang
      POSTGRES_PASSWORD: epoch2025zhang
      POSTGRES_DB: gzvg
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgsql/data:/var/lib/postgresql/data
    networks:
      - gzva_net

  mysql:
    image: mysql:8.0.43
    container_name: mysql
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
      # root 密码 - root password
      MYSQL_ROOT_PASSWORD: f4FMhWc6FdzuBCHf
    ports:
      - 3306:3306
    volumes:
      # 数据挂载 - Data mounting
      - ./data/mysql/data:/var/lib/mysql
      # 日志
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配) 
      # Modify the Mysql 8.0 default password strategy to the original strategy (MySQL8.0 to change its default strategy will cause the password to be unable to match)
      --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1
    privileged: true
    restart: always
    networks:
      - gzva_net

  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    ports:
      - 36379:6379
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    volumes:
      # 数据文件 - data files
      - ./data/redis/data:/data:rw
    command: "redis-server --requirepass GwAGt4UmTwcMhjun  --appendonly yes"
    privileged: true
    restart: always
    networks:
      - gzva_net

  nginx:
    build:
      context: ./deploy/nginx
      dockerfile: Dockerfile
    image: nginx-njs:1.2.8
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      # 挂载主配置文件（含全局设置）
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # 挂载子配置文件（虚拟主机配置）
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
      # 挂载 NJS 脚本
      - ./deploy/nginx/njs:/etc/nginx/njs:ro
    working_dir: /etc
    command: [ "nginx", "-g", "daemon off;" ]
    networks:
      - gzva_net
  
  etcd:
    image: quay.io/coreos/etcd:v3.5.7
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
    volumes:
      - ./data/etcd/data:/bitnami/etcd-data
    networks:
      - gzva_net

networks:
  gzva_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
